#!/bin/bash

# Include and exclude lists
INCLUDE_LIST=("*.py" "*.sh" "*.js" "*.go" "*.groovy" "*.yml" "*.yaml" "*.sql" "*.cpp" "*.hpp" "*.c" "*.h")

AUTO_GENERATED_STRING=("auto generated" "code generated" "DO NOT EDIT" "do not modify" "Created by" "auto-generated" "autogenerated")
COPYRIGHT_STRING=("Copyright IBM Corp" "© IBM Corp." "©️ Copyright IBM Corp")

# Get current year
EXPECTED_YEAR=$(date +"%Y")

# Arrays to track failed files by error type
MISSING_COPYRIGHT=()
INCORRECT_COPYRIGHT_YEAR=()

# Function to list changed files excluding vendor folders
list_changed() {
    if [ "$1" = "--no-delete" ]; then
        _changed_diff_filter="--diff-filter=d"
    else
        _changed_diff_filter=""
    fi

    # list changed files excluding deleted
    if [ -n "$HASH" ]; then
        git diff --name-only $_changed_diff_filter "$HASH" -- ':!golang/vendor'
    else
        git diff --name-only $_changed_diff_filter --cached -- ':!golang/vendor'
    fi 
}

# Function to check if a file matches a pattern
matches_pattern() {
    local file=$1
    shift
    local patterns=("$@")
    for pattern in "${patterns[@]}"; do
        if [[ "$file" == "$pattern" ]]; then
            return 0
        fi
    done
    return 1
}

# Check if the file contains auto-generated markers
contains_generated_code() {
    local file=$1
    for string in "${AUTO_GENERATED_STRING[@]}"; do
        if grep -q "$string" "$file"; then
            return 0
        fi
    done
    return 1
}

# Check if the file contains a copyright
contains_copyright() {
    local file=$1
    for string in "${COPYRIGHT_STRING[@]}"; do
        if grep -q "$string" "$file"; then
            return 0
        fi
    done
    return 1
}

# Check if the copyright year is correct
check_copyright_year() {
    local file=$1
    if grep -q "Copyright.*$EXPECTED_YEAR" "$file"; then
        return 0
    fi
    return 1
}

# Get the list of changed files using list_changed function
CHANGED_FILES=$(list_changed --no-delete)

# Process each changed file
for file in $CHANGED_FILES; do
    # Check against the include list
    if ! matches_pattern "$file" "${INCLUDE_LIST[@]}"; then
        continue
    fi

    # Skip files that are auto-generated
    if contains_generated_code "$file"; then
        continue
    fi

    # Check for missing copyright
    if ! contains_copyright "$file"; then
        MISSING_COPYRIGHT+=("$file")
        continue
    fi

    # Check for incorrect copyright year
    if ! check_copyright_year "$file"; then
        INCORRECT_COPYRIGHT_YEAR+=("$file")
    fi
done

# Report results
if [[ ${#MISSING_COPYRIGHT[@]} -gt 0 ]] || [[ ${#INCORRECT_COPYRIGHT_YEAR[@]} -gt 0 ]]; then
    echo "The following files failed validation:"

    if [[ ${#MISSING_COPYRIGHT[@]} -gt 0 ]]; then
        echo -e "\nMissing Copyright:"
        for file in "${MISSING_COPYRIGHT[@]}"; do
            echo "  - $file"
        done
    fi

    if [[ ${#INCORRECT_COPYRIGHT_YEAR[@]} -gt 0 ]]; then
        echo -e "\nIncorrect or Missing Copyright Year:"
        for file in "${INCORRECT_COPYRIGHT_YEAR[@]}"; do
            echo "  - $file"
        done
    fi

    exit 1
else
    echo "All files passed validation."
    exit 0
fi